# Battery level report interval in seconds
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
# Increase keyboard debounce
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# Change keyboard default display name
CONFIG_ZMK_KEYBOARD_NAME="Corne"
# Fix battery report related bug on Windows
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# OLED config
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
# Enable a widget to show words per minute
#CONFIG_ZMK_WIDGET_WPM_STATUS=n
#CONFIG_ZMK_WIDGET_LAYER_STATUS=n
#CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=n
# Bongo cat typing animation
#CONFIG_ZMK_WIDGET_BONGO_CAT=y

# Sleep config
# Milliseconds of inactivity before entering idle state (30 seconds)
CONFIG_ZMK_IDLE_TIMEOUT=30000
# Enable deep sleep support	
CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep (15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Mouse/pointing config
CONFIG_ZMK_POINTING=y

# ZMK Studio config
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# RGB config
CONFIG_ZMK_RGB_UNDERGLOW=y
# Turn off RGB when keyboard enters idle
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
